In [1]:
import numpy as np

# Numpy Array

In [7]:
print("1D array: ")
np.array([1.1,1,1,3,4,5])

1D array: 


array([1.1, 1. , 1. , 3. , 4. , 5. ])

In [8]:
print("2D array: ")
np.array([[1,1,1,3,4,5],[2,2,3,4,5,4],[1,2,2,4,5,3]])

2D array: 


array([[1, 1, 1, 3, 4, 5],
       [2, 2, 3, 4, 5, 4],
       [1, 2, 2, 4, 5, 3]])

In [9]:
print("3D array: ")
np.array([[[1,1,1,3,3,5],[1,2,2,4,5,3]],[[2,2,4,3,5,5],[1,2,2,4,5,3]],[[1,2,2,4,5,3],[1,2,2,4,5,3]]])

3D array: 


array([[[1, 1, 1, 3, 3, 5],
        [1, 2, 2, 4, 5, 3]],

       [[2, 2, 4, 3, 5, 5],
        [1, 2, 2, 4, 5, 3]],

       [[1, 2, 2, 4, 5, 3],
        [1, 2, 2, 4, 5, 3]]])

In [10]:
a=np.array([1.1,1,1,3,4,5])
print(type(a))

<class 'numpy.ndarray'>


In [11]:
print(a.size)

6


In [12]:
b=np.array([[1,1,1,3,4,5],[2,2,3,4,5,4],[1,2,2,4,5,3]])
print(b.size)

18


In [13]:
print(len(b))
print(len(a))

3
6


In [14]:
print(a.shape) 
print(b.shape)

(6,)
(3, 6)


In [15]:
c=np.array([[[1,1,1,3,3,5],[1,2,2,4,5,3]],[[2,2,4,3,5,5],[1,2,2,4,5,3]],[[1,2,2,4,5,3],[1,2,2,4,5,3]]])
print(c.shape)

(3, 2, 6)


In [16]:
d=c.transpose()
print(d)

[[[1 2 1]
  [1 1 1]]

 [[1 2 2]
  [2 2 2]]

 [[1 4 2]
  [2 2 2]]

 [[3 3 4]
  [4 4 4]]

 [[3 5 5]
  [5 5 5]]

 [[5 5 3]
  [3 3 3]]]


In [24]:
np.empty((2,2),dtype=int)

array([[-1378074682,   990266701],
       [ 2138817807, -1072668410]])

In [25]:
np.empty((3,4),dtype=float)

array([[7.96613837e-312, 2.81617418e-322, 0.00000000e+000,
        0.00000000e+000],
       [1.08221785e-312, 1.58817677e-052, 7.73660776e-091,
        6.01032905e-067],
       [5.54771274e+169, 1.60025725e+160, 6.48224660e+170,
        4.93432906e+257]])

In [26]:
np.ones((5,4),dtype=float)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [27]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [28]:
np.arange(1,21)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

# Array Operations

In [31]:
array1=np.arange(1,19).reshape(3,6)
array2=np.arange(1,19).reshape(3,6)
AddedArray1=array1+array2
AddedArray2=np.add(array1,array2)
print(AddedArray2)

[[ 2  4  6  8 10 12]
 [14 16 18 20 22 24]
 [26 28 30 32 34 36]]


In [33]:
SubtractedArray2=np.subtract(array1,array2)
print(SubtractedArray2)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]


In [34]:
MultipliedArray2=np.multiply(array1,array2)
print(MultipliedArray2)

[[  1   4   9  16  25  36]
 [ 49  64  81 100 121 144]
 [169 196 225 256 289 324]]


In [37]:
array2=array2.reshape(6,3)
multi=array1@array2
print(multi)

[[ 231  252  273]
 [ 537  594  651]
 [ 843  936 1029]]


In [38]:
print(multi,"\nMax: ",multi.max(),"\nMin: ",multi.min(),"\nindexMex: ",multi.argmax(),"\nindexMin: ",multi.argmin())

[[ 231  252  273]
 [ 537  594  651]
 [ 843  936 1029]] 
Max:  1029 
Min:  231 
indexMex:  8 
indexMin:  0


# Other operations

In [39]:
print(np.pi)
print(np.sin(np.pi/2))
print(np.sin(np.pi/6))
print(np.cos(np.pi/2))
print(np.cos(np.pi/6))
print(np.tan(np.pi/2))
print(np.tan(np.pi/6))

3.141592653589793
1.0
0.49999999999999994
6.123233995736766e-17
0.8660254037844387
1.633123935319537e+16
0.5773502691896257


In [40]:
rand=np.random.random(1)
print(rand)
rand=np.random.random(3)
print(rand)
rand=np.random.random((3,3))
print(rand)
rand=np.random.randint(1,15)
print(rand)
rand=np.random.randint(1,15,(3,3))
print(rand)
print(rand[1][2])

array=np.arange(1,100,7)
print(array)
a=np.random.choice(array)
print(a)

[0.96136699]
[0.68039631 0.2955072  0.95963966]
[[0.84278084 0.93433537 0.36334769]
 [0.60026591 0.04225851 0.76830692]
 [0.27786238 0.75248723 0.65271943]]
10
[[ 3 10  8]
 [13  8 10]
 [13  6  8]]
10
[ 1  8 15 22 29 36 43 50 57 64 71 78 85 92 99]
50
