In [1]:
import numpy as np
Array=np.random.randint(10,29,4)
Array

array([20, 19, 24, 21])

In [5]:

Array=np.arange(1,4).reshape(3,1)
Array2=np.arange(1,5).reshape(1,4)
print(Array2)
print(Array2)
print(Array+Array2)

[[1]
 [2]
 [3]]
[[1 2 3 4]]
[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [11]:
Array=np.random.randint(1,50,25).reshape(5,5)
print(Array)
Array[Array>15]=0
print(Array)

[[ 8 36  8 11 12]
 [37 20  9 29 33]
 [27 18 14  8 22]
 [ 1 19 40 34  2]
 [49  4 47 43 38]]
[[ 8  0  8 11 12]
 [ 0  0  9  0  0]
 [ 0  0 14  8  0]
 [ 1  0  0  0  2]
 [ 0  4  0  0  0]]


In [12]:
Array=np.array([1,2,3])
Array2=np.arange(1,13).reshape(4,3)
print(Array+Array2)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [13]:
Array=np.array([1,2,3])
Array2=np.arange(1,13).reshape(3,3)
print(Array+Array2)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [21]:
Array=np.array([1,2,3])
Array2=np.arange(1,26).reshape(5,5)
print(Array2[::2,::2])
print(Array+Array2[::2,::2])

[[ 1  3  5]
 [11 13 15]
 [21 23 25]]
[[ 2  5  8]
 [12 15 18]
 [22 25 28]]


In [38]:
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
print(array_2d)
print(array_2d[:,::-1])
print(array_2d[1::-1,::])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[4 5 6]
 [1 2 3]]


In [ ]:
array_3d = np.arange(120).reshape(4, 5, 6)
print(array_3d)
sub_array = array_3d[:2, :3, :4]
print(sub_array)
array_1d = np.array([10, 20, 30, 40])
result_array = sub_array + array_1d[np.newaxis, np.newaxis, :]
print("\nModified sub-array after adding the 1D array to each row:")
print(result_array)
