In [2]:
import numpy as np
Array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
random_numbers = np.random.randint(1, 21, size=9)
Array2D=random_numbers.reshape(3,3)
print(Array2D)
#second Method
Array2=np.random.randint(1,21,(3,3))
print(Array2)

[[11  7  3]
 [ 1  9 13]
 [ 7 17 15]]
[[ 6 18 12]
 [18  8 13]
 [ 6  3  5]]


In [4]:
Array3D=np.ones((2,3,4),dtype='int')
Array3D

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [6]:
Array1=np.array([1,2,3,4,5])
Array2=np.array([1,2,3,4,5])
Array1+Array2

array([ 2,  4,  6,  8, 10])

In [14]:
Array1=np.arange(1,10).reshape(3,3)
Array2=np.arange(21,30).reshape(3,3)
Array1*Array2

array([[ 21,  44,  69],
       [ 96, 125, 156],
       [189, 224, 261]])

In [16]:
Array1=np.arange(1,10).reshape(3,3)
Array2=np.arange(21,30).reshape(3,3)
np.dot(Array1,Array2)

array([[150, 156, 162],
       [366, 381, 396],
       [582, 606, 630]])

In [28]:
Array=np.arange(1,21)
print(np.mean(Array))
print(np.median(Array))
print(np.std(Array))

10.5
10.5
5.766281297335398


In [35]:
Array=np.arange(1,10).reshape(3,3)

print(np.max(Array))
print(np.min(Array))

9
1


In [37]:
Array=np.random.randint(10,50,(5,5))
print(Array)

[[36 47 36 19 21]
 [47 38 35 48 37]
 [16 40 11 46 23]
 [22 40 28 32 19]
 [49 35 16 12 31]]


In [39]:
Array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print(np.cumsum(Array))

[ 0  1  3  6 10 15 21 28 36 45]


In [41]:
Array=np.random.randint(10,50,(5,5))
np.corrcoef(Array)

array([[ 1.        , -0.24344936,  0.61429485, -0.08131959,  0.38969874],
       [-0.24344936,  1.        , -0.75820027,  0.40762215,  0.27021832],
       [ 0.61429485, -0.75820027,  1.        , -0.1315181 ,  0.192355  ],
       [-0.08131959,  0.40762215, -0.1315181 ,  1.        , -0.36530851],
       [ 0.38969874,  0.27021832,  0.192355  , -0.36530851,  1.        ]])

In [44]:
outcomes = np.random.randint(1, 7, size=1000)
frequency = {}
for num in outcomes:
    if num in frequency:
        frequency[num] += 1
    else:
        frequency[num] = 1
print(frequency)

{1: 179, 4: 155, 3: 177, 5: 165, 2: 166, 6: 158}


In [ ]:
#Extras

In [7]:

#choosing Random number from the list
Array=np.array([3,4,6,99,55,33,22,34,55])
np.random.choice(Array)

99

In [18]:
#changing dimention of array
Array=np.array([[1,1,1,3,4,5],[2,2,3,4,5,4],[1,2,2,4,5,3]])
Array2=np.array([[[1,1,1,3,3,5],
                  [1,2,2,4,5,3],
                  [2,2,4,3,5,5]],
                 
                  [[1,2,2,4,5,3],
                   [1,2,2,4,5,3],
                   [1,2,2,4,5,3]]])
print(Array.flatten())
print(Array2.flatten())

[1 1 1 3 4 5 2 2 3 4 5 4 1 2 2 4 5 3]
[1 1 1 3 3 5 1 2 2 4 5 3 2 2 4 3 5 5 1 2 2 4 5 3 1 2 2 4 5 3 1 2 2 4 5 3]


In [16]:
Array2=np.array([[[1,1,1,3,3,5],[1,2,2,4,5,3],[2,2,4,3,5,5],[1,2,2,4,5,3],[1,2,2,4,5,3]]])
np.transpose(Array2)

array([[[1],
        [1],
        [2],
        [1],
        [1]],

       [[1],
        [2],
        [2],
        [2],
        [2]],

       [[1],
        [2],
        [4],
        [2],
        [2]],

       [[3],
        [4],
        [3],
        [4],
        [4]],

       [[3],
        [5],
        [5],
        [5],
        [5]],

       [[5],
        [3],
        [5],
        [3],
        [3]]])

In [20]:
#Swaping axis of an array
Array2=np.array([[[1,1,1,3,3,5],
                  [1,2,2,4,5,3],
                  [2,2,4,3,5,5]],
                 
                  [[1,2,2,4,5,3],
                   [1,2,2,4,5,3],
                   [1,2,2,4,5,3]]])
SwappedArray = np.swapaxes(Array2, 0, 1)
print(SwappedArray)

[[[1 1 1 3 3 5]
  [1 2 2 4 5 3]]

 [[1 2 2 4 5 3]
  [1 2 2 4 5 3]]

 [[2 2 4 3 5 5]
  [1 2 2 4 5 3]]]


In [22]:
#create an array fill with specific value
Array = np.full((2, 3), 'false')
print(Array)

[['false' 'false' 'false']
 ['false' 'false' 'false']]


Given a 2D array of shape (6, 6), extract a 2x2 sub-array starting from the element at position (1, 1).

In [29]:
Array=np.arange(1,37).reshape(6,6)
Array[1:3,1:3]

array([[ 8,  9],
       [14, 15]])

From a 3D array of shape (3, 2, 1), extract all elements in the first two rows and all columns of the second slice along the third axis.


In [35]:
Array=np.arange(1,7).reshape(3,2,1)
print(Array)
print(Array[1,:,0])

[[[1]
  [2]]

 [[3]
  [4]]

 [[5]
  [6]]]
[3 4]


In [37]:
Array = np.array([0, 1, 5, 65, 323, 53, 6453, 2327, 8,34239])
Index=[1,3,4,6]
Array[Index]

array([   1,   65,  323, 6453])

In [57]:
Array = np.array([[1, 5, 65,4],[ 323, 53, 6453,5],[ 2327, 8,34239,3]])
rows=[0,2,2]
Coloumns=[1,3]
Array[rows,:][:,Coloumns]

array([[5, 4],
       [8, 3],
       [8, 3]])

In [58]:
Array=np.random.randint(1,20,12)
Array[Array>8]

array([18,  9, 12, 15, 13, 17,  9, 18,  9])